### ISSUE TITLE
directory traversal

### ISSUE THREAD

**Issue by JanKoppe** [o2r-project/o2r-contentbutler#1]
mitigations for directory traversal are missing.

**Comment by nuest** [comment]
Why must something be mitigated? Please clarify.

**Comment by nuest** [comment]
A quick test with `localhost/api/v1/compendium/821zh/data/../../../../` resulted in a redirect to `http://localhost/api/`..., also if using `%2e%2e%2f` or `%2e%2e/`. Requests don't even make it into the microservice.
