### ISSUE TITLE
documentation/example nginx integration

### ISSUE THREAD

**Issue by JanKoppe** [o2r-project/o2r-contentbutler#3]
write a doc explaining how to integrate this service with e.g. nginx. location with regular expressions seem to be the easiest way.

**Comment by nuest** [comment]
So to integrate the different microservices, they have to be added to the nginx configuration?

Maybe you could check if there is a (very lightweight and easy to use) discovery library, see http://microservices.io/patterns/server-side-discovery.html

But we should only do this if it is actually less work than edition the nginx file... if properly documented in each microservics README, then that might be the more reasonable solution.

**Comment by nuest** [comment]
Long solved, see project o2r-platform.
