### ISSUE TITLE
Renaming?!

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-contentbutler#7]
@JanKoppe was not really happy with the name... in line with "muncher" I suggest to make it at least "a person"/use active voice, so rename to `o2r-dataserver`. And then it's not far to [butlers](https://en.wikipedia.org/wiki/List_of_fictional_butlers)

@JanKoppe Do you imagine this microservice also being the one serving access to complete compendia? Or would you do that in a different one? In case of a different one, a more focussed name would be `o2r-contentbutler`, the one for complete compendia could be `o2r-compendiumbutler`

**Comment by JanKoppe** [comment]
"butler" is a nice idea, I like it.

@nuest Can you elaborate on what "serving access to complete compendia" should look like? Do we want to provide a archive (e.g. zip, tar, …) that contains the complete compendium (in BagIt format)? If so, then this would be a good point to split those services, IMHO. Your proposed names LGTM.

**Comment by JanKoppe** [comment]
5a03fae7c17464349ed147f9fd6d15c1dcb5d02e renamed to contentbutler.

**Comment by nuest** [comment]
Yes, complete compendia would be archives in BagIt format containing the content, the Dockerfile, and the docker image (!).

**Comment by nuest** [comment]
One more nice thing about the "butler" is that we can try to distinguish between things that "we" have in our database (accessed by muncher and others directly) and stuff we might have to fetch from a remote repository, which is done by xyz-butler.
